### PR TITLE
Remove password echoing & add devops-insight.properties file in component helm chart

### PR DESCRIPTION
**Pull request by jauninb**
Remove password echoing & add devops-insight.properties file in component helm chart

### CODE REVIEW

**Comment by jauninb** [comment]
@hmagph Can you pls review and merge ?

**Comment by jauninb** [comment]
Additional information:
- `grep -v` addition is to filter out password line in the logs
- for devops-insights.properties in the packaged chart file, this is to identify the elements required to link a deployment action (using only the .tgz file in ICP) to a deployment record in DevopsInsights
- `fetch_git_creds.sh`: this script is only to retrieve git creds and stored it in build.properties. Its goal is not to copy the working dir in the archive dir. (for microservices template: in the CI pipeline, the archive_dir is at the root - ie `.` so no impact, in the CD pipeline, this is the `build_umbrella_chart.sh` that is copying the just builded artifacts in the archive dir). 
- `image_tag` related update: `image_tag` was not defined for the build_umbrella_chart action - it is only
used in the build_component_chart
- the reference to `jauninb` will need to be removed to reference the `open-toolchain\next` branch when accepted

**Comment by jauninb** [comment]
I made tests to use the `jauninb/commons` fork (`next` branch) by instanciating:
- microservices-helm-toolchain: https://github.com/open-toolchain/microservices-helm-toolchain
- java-helm-toolchain: https://github.com/open-toolchain/java-helm-toolchain

Both thoses tests were successfull with the usage of the fork/next version of the scripts (ie the purpose of this PR)

**Comment by jauninb** [comment]
@hmagph do you need some additional info ?

**Review by hmagph — APPROVED** [review]

**Pull request merged**
