### PR TITLE
Restrict to namespace when listing existing images

### PR DESCRIPTION
**Pull request by jerome-lanneluc**
Listing existing images can be a very expensive operation when you have thousands of existing images. It can last several minutes.

### CODE REVIEW

**Comment by briangleeson** [comment]
Alternative option, use a more selective image list request: `ibmcloud cr images --restrict ${REGISTRY_NAMESPACE}`

**Comment by jerome-lanneluc** [comment]
I like this alternative option. Updated the PR to restrict to the registry namespace.

**Comment by jauninb** [comment]
The update with --restrict is not required as this is done also later in the script
The initial ibmcloud cr images was just here to provide contextuel information
This can be done using a guard if if PIPELINE_DEBUG or similar

**Comment by othomann** [comment]
Would be good to get either solution merged in ? This would make the time spent for the pipeline more predictable.

**Comment by othomann** [comment]
If the goal was just to provide contextual information, I would vote to remove the call completely like the first commit @jerome-lanneluc provided.

**Comment by jerome-lanneluc** [comment]
Agreed. Listing of existing images have been removed.

**Review by jauninb — APPROVED** [review]
LGTM

**Comment by jerome-lanneluc** [comment]
Change made in source repo: https://github.ibm.com/open-toolchain/commons/pull/4

**Comment by othomann** [comment]
thank you all!

**Comment by maire-kehoe** [comment]
Just adding a link. This change is in the commit:
- Do not list existing images
   https://github.com/open-toolchain/commons/commit/e6b7cf19251028f04aba02f674b4c0ff01a4ff64

**Pull request closed without merging**
